production:
  adapter: sqlite3
  database: ~/.kindle/kindle-database.sqlite

development:
  adapter: sqlite3
  database: ~/.kindle/database-dev.sqlite

test:
  adapter: sqlite3
  database: ~/.kindle/database-test.sqlite
