production:
  adapter: sqlite3
  database: ~/.kindle/kindle.db

development:
  adapter: sqlite3
  database: ~/.kindle/database-dev.sqlite

test:
  adapter: sqlite3
  database: ~/.kindle/database-test.sqlite
