production:
  adapter: sqlite
  database: kindle
  file: ~/.kindle/database.sqlite

development:
  adapter: sqlite
  database: kindle
  file: ~/.kindle/database-dev.sqlite

test:
  adapter: sqlite
  database: kindle
  file: ~/.kindle/database-test.sqlite
